name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:

      - name: checkout sources
        uses: actions/checkout@v2

      - name: install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: build default
        run: cargo build --verbose --release

  test-lmdb:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: test
        run: cargo test --release -p yrs-lmdb --lib

  test-rocksdb:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: test
        run: cargo test --release -p yrs-rocksdb --lib